GET http://localhost:3000/

###
POST http://localhost:3000/
content-type: application/json

{ 
  "taskDeatils": {
    "createdAt": "2022-09-07T10:21:15.000Z",
    "deadline": "2022-09-07T10:21:15.000Z",
    "priority": "Medium",
    "taskName": "Test 3"
  }
}


###
DELETE http://localhost:3000/
content-type: application/json

{
  "id": "631863a909d368525289c42b"
}
