GET http://localhost:3000/

###
GET http://localhost:3000?priority=High


###
POST http://localhost:3000/
content-type: application/json

{ 
  "taskDeatils": {
    "createdAt": "2022-09-07T10:21:15.000Z",
    "deadline": "2022-09-07T10:21:15.000Z",
    "priority": "Low",
    "taskName": "Test 1"
  }
}


###
DELETE http://localhost:3000/
content-type: application/json

{
  "id": "632b10103bb4d5d68c2573e4"
}
